version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
      - image: circleci/mongo
        command: --port 5000
    steps:
      - run:
         name: test
         command:  sleep 10
